#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG="/usr/bin/ddns-go"
CONF="/etc/ddns-go/ddns-go-config.yaml"

start_service() {
	config_load ddns-go

	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	config_get listen main listen ':9876'
	config_get interval main interval '300'
	config_get cache_times main cache_times '5'
	config_get dns main dns ''
	config_get_bool skip_verify main skip_verify 0
	config_get_bool no_web main no_web 0

	mkdir -p /etc/ddns-go

	procd_open_instance
	procd_set_param command "$PROG"
	procd_append_param command -c "$CONF"
	procd_append_param command -l "$listen"
	procd_append_param command -f "$interval"
	procd_append_param command -cacheTimes "$cache_times"
	[ -n "$dns" ] && procd_append_param command -dns "$dns"
	[ "$skip_verify" -eq 1 ] && procd_append_param command -skipVerify
	[ "$no_web" -eq 1 ] && procd_append_param command -noweb
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger ddns-go
}
