include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for DDNS-GO
LUCI_DEPENDS:=+luci-base +ddns-go
LUCI_PKGARCH:=all

PKG_LICENSE:=MIT
PKG_MAINTAINER:=Accelerator6666

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
